# Generated by Django 5.0.6 on 2024-07-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 13, 9, 42, 660623, tzinfo=datetime.timezone.utc)),
        ),
    ]
